language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - SHELLCHECK_OPTS=""

#services:

#  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - shellcheck

install:
  - pip install -r station/requirements.txt
  - pip install -r server/requirements.txt
  - pip install pytest

before_script:
  - psql -c 'create database svarog;' -U postgres
  - cp server/.svarog.ini.travis server/svarog.ini
  - cd server && python migrate_db.py && cd ..
  - psql -f server/tests/db-data.psql svarog
  - mkdir -p ~/.config/svarog-gut

script:
  - cd station && pytest -v ; cd ..
  - cd server && PYTHONTEST=. pytest -v ; cd ..
  - find . -name '*.sh' | xargs shellcheck ${SHELLCHECK_OPTS}

notifications:
  email:
    recipients:
      - spam.travis@klub.com.pl
    on_success: change
    on_failure: always
