import subprocess
from typing import Callable, Iterable, Optional, TypeVar

def coords(lon, lat):
    t = "%2.4f" % lat
    if (lat>0):
        t += "N"
    else:
        t += "S"

    t += " %2.4f" % lon
    if (lon>0):
        t += "E"
    else:
        t += "W"
    return t

def make_thumbnail(input_path, output_path, width=200):
    subprocess.check_call(["convert" ,"-thumbnail", str(width), input_path, output_path])

T = TypeVar("T")
def first(condition: Callable[[T], bool], items: Iterable[T]) -> Optional[T]:
    '''Return first element for which @condition is True. Otherwise return None'''
    for item in items:
        if condition(item):
            return item
    return None

def get_footer():
    """Generates page footer. Tries to load timestamp.txt (which is generated by update.sh script)"""
    version = "unknown"
    try:
        f = open("timestamp.txt", 'r')
        version = f.read()
        return "Version <a href='https://github.com/gut-space/satnogs/commit/%s'>%s</a>" % (version, version)
    except FileNotFoundError:
        return "Version unknown"
