name: Pylint station

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 wheel
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi

    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=.:server/ pylint --rcfile .pylint $(git ls-files 'server/*.py')
    - name: Lint with flake8
      run: |
        PYTHONPATH=.:server/ flake8 --config .flake8.ini --color=auto $(git ls-files 'server/*.py')
