# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Server testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd server
        pwd
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd server
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --exclude venv/ --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Setup database
      run: |
        psql -c 'create database svarog;' -U postgres
        cp server/.svarog.ini.travis server/svarog.ini
        cd server && python migrate_db.py && cd ..
        psql -f server/tests/db-data.psql svarog
        mkdir -p ~/.config/svarog-gut

    - name: Test with pytest
      run: |
        cd server

        # this is a kludge. It should work without explicit filenames (just pytest), but it
        # doesn't.
        PYTHONPATH=. pytest -s -v tests/test*.py
